create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  subtitle text,
  category text not null check (category in ('software', 'infrastructure')),
  description text not null,
  top_tag text,
  tech_stack text[] default '{}'::text[],
  status_label text default '✓ Active Deployment',
  live_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  ip_address text,
  page_visited text,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.messages (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;
alter table public.visitors enable row level security;
alter table public.messages enable row level security;

create policy "Public can read projects"
  on public.projects for select
  using (true);

create policy "Public can insert visitors"
  on public.visitors for insert
  with check (true);

create policy "Public can read visitors for admin"
  on public.visitors for select
  using (true);

create policy "Public can insert messages"
  on public.messages for insert
  with check (true);

create policy "Public can read messages for admin"
  on public.messages for select
  using (true);

create policy "Public can update projects"
  on public.projects for update
  using (true)
  with check (true);

create policy "Public can delete projects"
  on public.projects for delete
  using (true);

create policy "Public can insert projects"
  on public.projects for insert
  with check (true);

create index if not exists idx_projects_category on public.projects(category);
create index if not exists idx_projects_created_at on public.projects(created_at desc);
create index if not exists idx_visitors_created_at on public.visitors(created_at desc);
